global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  routes:
  - match:
      alertname: HighUsage
  receiver: 'scale-out-senlin'
receivers:
- name: 'scale-out-senlin'
  webhook_configs:
  - url: 'http://10.0.20.10:8778/v1/webhooks/789850f1-7836-4446-a7a2-e94470491e67/trigger?V=2'
    send_resolved: false
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
